name: DevSecOps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar Pytest
        run: |
          pytest

      - name: Ejecutar Bandit
        run: |
          bandit -r . -x ./tests

      - name: Construir imagen Docker
        run: |
          docker build -t devsecops-api:${{ github.sha }} .

      - name: Instalar Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            gpg --dearmor | \
            sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] \
            https://aquasecurity.github.io/trivy-repo/deb \
            $(lsb_release -sc) main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Escanear imagen con Trivy
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL devsecops-api:${{ github.sha }}
